modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Bottled%20Air"
logoFile="icon.png"

[[mods]]
modId="bottledair"
version="2.1"
displayName="Bottled Air"
displayURL="https://curseforge.com/minecraft/mc-mods/bottled-air"
authors="Rick South"
description='''Allows players to breathe in empty glass bottles underwater to get more air, configurable.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.bottledair]]
    modId="collective"
    mandatory=true
    versionRange="[6.45,)"
    ordering="NONE"
    side="BOTH"